# Generated by Django 3.1.6 on 2021-02-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcsv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='created',
        ),
        migrations.RemoveField(
            model_name='schemacolumn',
            name='created',
        ),
        migrations.AlterField(
            model_name='schema',
            name='delimiter',
            field=models.CharField(choices=[(',', 'Comma ( , )'), (';', 'Semicolon ( ; )'), ('\t', 'Tab ( \\t )'), ('|', 'Pipe ( | )')], default=(',', 'Comma ( , )'), max_length=1, verbose_name='Column separator'),
        ),
        migrations.AlterField(
            model_name='schemacsv',
            name='ready',
            field=models.BooleanField(db_index=True, default=False, null=True, verbose_name='Status'),
        ),
    ]
